// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbsxyvclylkclixwsytr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpic3h5dmNseWxrY2xpeHdzeXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzIxODEsImV4cCI6MjA1OTk0ODE4MX0.3Y5MYryKBOk1ROx2p0ieI7ZwEXy9r3fQn6Mf65VbIfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);